[supervisord]
nodaemon=true

[program:django]
command=bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:7860"
autostart=true
autorestart=true
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:whatsappbot]
command=npm start
autostart=true
autorestart=true
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
