# Generated by Django 6.0.7 on 2026-09-22 19:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_splitgroup_share_token_alter_expense_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.CharField(max_length=100)),
                ('creditor', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='tracker.splitgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
